import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ width: "100%", height: "0.5rem", overflow: "visible" }}
      >
        <div className="w-screen overflow-y-scroll bg-white h-100vw overflow-visible">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
